# Form implementation generated from reading ui file '.\uis\PushToCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 371)
        Dialog.setMinimumSize(QtCore.QSize(400, 64))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelChooseCalendar = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelChooseCalendar.sizePolicy().hasHeightForWidth())
        self.labelChooseCalendar.setSizePolicy(sizePolicy)
        self.labelChooseCalendar.setMinimumSize(QtCore.QSize(0, 0))
        self.labelChooseCalendar.setObjectName("labelChooseCalendar")
        self.horizontalLayout.addWidget(self.labelChooseCalendar)
        self.comboBoxCalendars = QtWidgets.QComboBox(parent=Dialog)
        self.comboBoxCalendars.setObjectName("comboBoxCalendars")
        self.horizontalLayout.addWidget(self.comboBoxCalendars)
        self.buttonUpdate = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUpdate.sizePolicy().hasHeightForWidth())
        self.buttonUpdate.setSizePolicy(sizePolicy)
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.horizontalLayout.addWidget(self.buttonUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelPlanUntil = QtWidgets.QLabel(parent=Dialog)
        self.labelPlanUntil.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.labelPlanUntil.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelPlanUntil.setObjectName("labelPlanUntil")
        self.verticalLayout.addWidget(self.labelPlanUntil)
        self.calendar = QtWidgets.QCalendarWidget(parent=Dialog)
        self.calendar.setGridVisible(False)
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        self.buttonPush = QtWidgets.QPushButton(parent=Dialog)
        self.buttonPush.setEnabled(False)
        self.buttonPush.setObjectName("buttonPush")
        self.verticalLayout.addWidget(self.buttonPush)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PushToCalendar"))
        self.labelChooseCalendar.setText(_translate("Dialog", "Choose Calendar"))
        self.buttonUpdate.setText(_translate("Dialog", "Update"))
        self.labelPlanUntil.setText(_translate("Dialog", "Plan Until"))
        self.buttonPush.setText(_translate("Dialog", "Push"))
